### ISSUE TITLE
The module is not on NPM

### ISSUE THREAD

**Issue by beshur** [vue-youtube/vue-youtube#1]
When trying on install I get the error:

> yarn add @vue-youtube/core
> error An unexpected error occurred: "https://registry.yarnpkg.com/@vue-youtube%2fcore: Not found".

**Comment by Techassi** [comment]
Hey @beshur. Yeah this package is not released yet. It will be soon tho and the old `techassi@vue-youtube-iframe` will be deprecaded.

**Comment by Techassi** [comment]
It is now released on npm. The old plugin is deprecated.

**Comment by beshur** [comment]
Thanks, awesome!
