### ISSUE TITLE
Issue with peer dependencies

### ISSUE THREAD

**Issue by Kelketek** [vue-youtube/vue-youtube#18]
Attempting to install while using Vue 3 is giving me trouble, due to the peer dependency requirements for Vue 2. Since Vue 2 is now end of life, you may be able to commit a 'last supported' version and then drop the Vue 2 peer dependencies to resolve this. Here's the error I received:

```
❯ npm install @vue-youtube/core                                                                                                                                    ─╯
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: artconomy@3.0.0
npm ERR! Found: vue@3.4.15
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.19" from @hcaptcha/vue3-hcaptcha@1.3.0
npm ERR!   node_modules/@hcaptcha/vue3-hcaptcha
npm ERR!     @hcaptcha/vue3-hcaptcha@"^1.3.0" from the root project
npm ERR!   peer vue@"2.x || 3.x" from @sentry/vue@7.92.0
npm ERR!   node_modules/@sentry/vue
npm ERR!     @sentry/vue@"^7.92.0" from the root project
npm ERR!   13 more (@tato30/vue-pdf, @vitejs/plugin-vue, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @vue-youtube/core@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@3.4.21
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.7.2" from @vue-youtube/core@0.0.6
npm ERR!     node_modules/@vue-youtube/core
npm ERR!       @vue-youtube/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/fox/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fox/.npm/_logs/2024-03-03T17_20_14_015Z-debug-0.log
```

**Comment by Techassi** [comment]
Ah yeah, I guess it makes sense to drop Vue 2 support then.

I will update this issue when I released a new version without Vue 2 support.

**Comment by Techassi** [comment]
This seems to be related to #14. What Vue version do you use for your project? This plugin currently requires `^3.3.7`, but I was considering to slightly lower the minimum required version.

**Comment by Kelketek** [comment]
@techassi I'm currently updating to `3.4.21`. It's possible that I was using a lower one when filing this issue. I ended up just sticking the standard embed code in for the meantime, which works mostly fine. I can try again soon with the latest version if you like.

**Comment by Techassi** [comment]
I would be happy to hear if it works for you with a version above `3.3.7`. Let me know how it goes!

**Comment by Kelketek** [comment]
@Techassi It installs with the current version of Vue, `3.4.21`, yes.

**Comment by Techassi** [comment]
Alright, good to hear! Can this issue be closed then?
