### ISSUE TITLE
Autoplay issue

### ISSUE THREAD

**Issue by cadilhac** [vue-youtube/vue-youtube#21]
I have 2 issues.

I have the component set up like this:

`<youtube-iframe :video-id="youtubeVideoId" :player-vars="{ autoplay: 1 }"  />`

It does not autoplay. If I add mute:1 for instance, then it autoplays and is muted.

The second issue is this: when I first load a page with this component, it shows a video corresponding to the route params and it does not autoplay (and it's normal because this time I did not add autoplay in the params, so by default it's 0). But if I click a link that goes to the same route (with different route params and therefore another video id), then the video autoplays (and specifying autoplay:0 does not help).

Any idea?

**Comment by cadilhac** [comment]
I just read in your doc that changing the video id triggers play. Why?
And so, how do I prevent this in my case of a route change where the page is rerendered with different params, including the video id?

**Comment by Techassi** [comment]
Partial response. I will answer your other questions when I'm back on my PC.

> It does not autoplay. If I add mute:1 for instance, then it autoplays and is muted.

This is normal browser behaviour. Browsers do not permit to play videos (with sound) without any prior interaction with the page (for example clicking). Thus, autoplay only works when the video is muted.

> I just read in your doc that changing the video id triggers play. Why?
And so, how do I prevent this in my case of a route change where the page is rerendered with different params, including the video id?

Yes, this behaviour is based on a personal need I had when developing the package. But I can see why someone wants to disable that. I can make it customizable using a config option. Expect a new release with that option soon :smile:

**Comment by Techassi** [comment]
Hey @cadilhac, please take a look at #23.

You can now customize the `onVideoIdChange` behaviour. You can either select `play` (default) to automatically play the video upon ID change or `cue` to only queue the new video.

Let me know if that satisfies your needs.

**Comment by cadilhac** [comment]
I had to choose another solution at that time. But thanks, this is good to know for the future.

**Comment by Techassi** [comment]
Alright, that's fair. I will go ahead and merge the PR and close this issue.
