### ISSUE TITLE
Error Installing with pnpm

### ISSUE THREAD

**Issue by FerryAr** [vue-youtube/vue-youtube#3]
OS: Manjaro Linux x64
pnpm version : 7.9.0

![Screenshot_2022-08-10_15-10-28](https://user-images.githubusercontent.com/38641932/183850393-79d8a468-883f-4e8b-8ff4-6667de5793cc.png)

**Comment by Techassi** [comment]
I will look into it.

**Comment by Techassi** [comment]
This should be fixed with version `0.0.2`. Let me know if it works.
