### ISSUE TITLE
player.seekTo() support?

### ISSUE THREAD

**Issue by CodyBontecou** [vue-youtube/vue-youtube#5]
I've looked through the code of `usePlayer` and haven't seen anything relating to the `seekTo` function discussed in Youtube's [docs](https://developers.google.com/youtube/iframe_api_reference#Playback_controls).

Is this feature supported here? If not, any plans on implementing it?

**Comment by Techassi** [comment]
There is no direct function you can destructure from the `usePlayer` composable. But you should be able to access it via the exposed `instance`.

```ts
const player = ref();
const { instance } = usePlayer('dQw4w9WgXcQ', player);

instance.value?.seekTo(); // Fully typed
```

Currently I feel like there is no need to directly expose each method the player provides via the `usePlayer` composable. The composable provides direct access to the most common methods but not all of them.

**Comment by CodyBontecou** [comment]
Cool, this works.

**Comment by Techassi** [comment]
Great, love to hear that!

**Comment by suterma** [comment]
I have done this, so I can second that this works. I would like to promote https://github.com/vue-youtube/docs/issues/3 here, because this would exactly address this question.
