### ISSUE TITLE
How to watch video instance's getCurrentTime()

### ISSUE THREAD

**Issue by CodyBontecou** [vue-youtube/vue-youtube#6]
Is there a way to use a Vue watcher on the video instance object that is created when doing this:

```
const { instance } = usePlayer(videoId, youtube)
```

**Comment by Techassi** [comment]
No there is no way to do this and I'm afraid this isn't possible to implement in the future.

In Vue we can only watch refs, but the `instance` methods don't return refs, as they are not designed to do so. The `instance` is the plain player instance which the YouTube API provides (see [here](https://developers.google.com/youtube/iframe_api_reference#Operations)).

Currently you can implement a hacky watcher-ish solution:

```ts
const currentTime = ref(0);
const yt = ref();

const { instance } = usePlayer(videoId, yt);

setInterval(() => {
  currentTime.value = instance.value?.getCurrentTime() || 0;
}, 100);
```
This is 100 percent not elegant nor very perfomance optimized. So use with caution!

**Comment by suterma** [comment]
Sorry, late, but I would like to throw in my 2cents. I have done this, with "requestAnimationFrame" though, so it's definitely possible and it also does perform well in my view.

See my code (extract from https://github.com/suterma/replayer-pwa/blob/main/src/code/media/YoutubeMediaHandler.ts#L20):

```
    /** The YouTube player instance to act upon */
    private _player: Player;

    get currentTime(): number {
        return this._player.getCurrentTime();
    }

    updateCurrentTime() {
        const currentTime = this.currentTime;
        this.onCurrentTimeChanged.emit(currentTime);
        if (this._player.getPlayerState() == PlayerState.PLAYING) {
            window.requestAnimationFrame(() => this.updateCurrentTime());
        }
    }
```
One could also throttle the events, if deemed useful.
