### ISSUE TITLE
Failed to build using webpack with version 0.0.3 - add support for ESM

### ISSUE THREAD

**Issue by Magiczne** [vue-youtube/vue-youtube#7]
When using version 0.0.3 inside webpack built environment error appears:

```
Module build failed: Error: ENOENT: no such file or directory, 
open '<redacted>/node_modules/@vue-youtube/component/dist/index.mjs'
```

**Comment by Techassi** [comment]
Thanks for pointing this out!

I have support for ESM modules, but there is an error in the `package.json` files. They reference `*.mjs` for ESM and `*.js` for CommonJS but should reference `*.js` and `*.cjs` respectively.

This will be fixed in version `0.0.4` which will be released shortly.

**Comment by Techassi** [comment]
This should now be fixed with [1a15878](https://github.com/vue-youtube/vue-youtube/commit/1a1587844970dd813b2831910459132e1428df58) and version [v0.0.4](https://github.com/vue-youtube/vue-youtube/releases/tag/v0.0.4).

**Comment by Magiczne** [comment]
@Techassi Thanks a lot, will check tommorow.

**Comment by Magiczne** [comment]
@Techassi works indeed, thanks!
